#! /bin/sh

set -e

case "$1" in
  remove|purge)
    if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
        /usr/lib/gdm/gdm-set-default-session --remove xubuntu || true
    fi
    ;;
esac

#DEBHELPER#
