#! /bin/sh

set -e

#DEBHELPER#

case "$1" in
  configure|upgrade)
    if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
        /usr/lib/gdm/gdm-set-default-session --keep-old xfce || true
    fi
    ;;
esac
