#! /bin/sh

set -e

LASTVER="11.04.0~"

if dpkg-maintscript-helper supports rm_conffile; then
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/applications/defaults.list "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/Thunar/volmanrc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/mount.rc "$LASTVER" -- "$@"
fi

case "$1" in
  remove|purge)
    if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
        /usr/lib/gdm/gdm-set-default-session --remove xubuntu || true
    fi
    ;;
esac

#DEBHELPER#
