#! /bin/sh

set -e

case "$1" in
  upgrade)
    if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
        /usr/lib/gdm/gdm-set-default-session --keep-old xubuntu || true
    fi
    ;;
  configure)
    if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
        /usr/lib/gdm/gdm-set-default-session --keep-old xubuntu || true
    fi
    ;;
esac

#DEBHELPER#
