#! /bin/sh

set -e

LASTVER="11.04.0~"

if dpkg-maintscript-helper supports rm_conffile; then
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/applications/defaults.list "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/Thunar/volmanrc "$LASTVER" -- "$@"
fi

#DEBHELPER#
