#! /bin/sh

set -e

LASTVER="11.04.5"

if dpkg-maintscript-helper supports rm_conffile; then
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/applications/defaults.list "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/Thunar/volmanrc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/mount.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/actions-6.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/clock-5.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/launcher-2.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/launcher-3.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/pager-3.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/panels.xml "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/places-2.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/separator-3.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/systray-4.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/tasklist-2.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/xfce4-menu-1.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/xfce4-mixer-plugin-5.rc "$LASTVER" -- "$@"
  dpkg-maintscript-helper rm_conffile \
    /etc/xdg/xdg-xubuntu/xfce4/panel/xfce4-orageclock-plugin-7.rc "$LASTVER" -- "$@"
fi

#DEBHELPER#
