#! /bin/sh

set -e

if dpkg-maintscript-helper supports mv_conffile; then
  dpkg-maintscript-helper mv_conffile \
    /etc/xdg/xdg-xubuntu/lightdm/lightdm-gtk-greeter.conf \
    /etc/lightdm/lightdm-gtk-greeter.conf.d/30_xubuntu.conf \
    15.10.1 -- "$@"
  dpkg-maintscript-helper mv_conffile \
    /etc/lightdm/lightdm-gtk-greeter.conf.d/30_xubuntu.conf \
    /usr/share/lightdm/lightdm-gtk-greeter.conf.d/30_xubuntu.conf \
    16.04.1 -- "$@"
fi

#DEBHELPER#

exit 0
